Vagrant.configure("2") do |config|
  config.vm.define "SRV-ANS" do |srv|
    srv.vm.box = "almalinux/8"
    srv.vm.hostname = "SRV-GIT"
    srv.vm.network "public_network", bridge:"Qualcomm Atheros QCA61x4A Wireless Network Adapter"
    srv.vm.provider "virtualbox" do |v|
      v.cpus = 1 
      v.memory = 1024
    end
  end
  config.vm.define "CLI-01" do |cli_01|
    cli_01.vm.box = "almalinux/8"
    cli_01.vm.hostname = "CLI-01"
    cli_01.vm.network "public_network", bridge:"Qualcomm Atheros QCA61x4A Wireless Network Adapter"
    cli_01.vm.provider "virtualbox" do |v|
      v.cpus = 1 
      v.memory = 1024
    end
  end
  config.vm.define "CLI-02" do |cli_02|
    cli_02.vm.box = "almalinux/8"
    cli_02.vm.hostname = "CLI-02"
    cli_02.vm.network "public_network", bridge:"Qualcomm Atheros QCA61x4A Wireless Network Adapter"
    cli_02.vm.provider "virtualbox" do |v|
      v.cpus = 1 
      v.memory = 1024
    end
  end
end